# Resources:
# - `man foot.ini` (https://man.archlinux.org/man/foot.ini.5.en)

[main]
# pad = 8x8 center
font = CaskaydiaMono Nerd Font:size=14
# shell = nu

# default dark theme
include = ~/.config/foot/themes/monokai.ini

# default light theme
include = ~/.config/foot/themes/catppuccin_latte.ini

# generated theme based on wallpaper
include = ~/.config/foot/themes/matugen.ini

[key-bindings]
show-urls-launch = Control+o
show-urls-persistent = Control+Shift+o
color-theme-toggle = Control+t

# TODO: ctrl+shift+n to spawn new terminal in $(pwd)

